#!/bin/bash
for rho in 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
do
    filename=$rho/output
# extract value from logfile
P=$( cat $filename | awk '/Average/ { print $4; }' )
#igpressure=$rho
#let "igpressure*=2.0"
# add values to result file
echo "$rho $igpressure $P" >> Pressures
done

